[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[data]
name = "open-r1/codeforces-cots"
split = "solutions_w_editorials_decontaminated"
max_seq_length = 1024

[wandb]
project = "DEMO"
name = "demo_1"

[checkpoint]
interval = 1

[eval]
model_name = "Qwen/Qwen2.5-0.5B-Instruct"
dataset_name = "livecodebench/code_generation_lite"
lcb_version = "v6"
num_samples = 256
