[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[data]
name = "open-r1/codeforces-cots"
split = "solutions_w_editorials_decontaminated"
max_seq_length = 1024

[wandb]
project = "DEMO"
name = "demo_1"

[profiler]
enabled = true
wait = 0
warmup = 1
active = 3
repeat = 1
output_dir = "outputs/profiler"

[checkpoint]
interval = 1

[eval]
model_name = "Qwen/Qwen2.5-0.5B-Instruct"
dataset_name = "livecodebench/code_generation_lite"
lcb_version = "v6"
num_samples = 256
lcb_custom_evaluate = true
lcb_custom_evaluator_module = "lcb_runner.runner.custom_evaluator"
lcb_custom_eval_args = ["--release_version", "v6"]
eval_batch_size = 4
