[model]
name = "Qwen/Qwen2.5-1.5B-Instruct"

[data]
name = "open-r1/codeforces-cots"
split = "solutions_w_editorials_decontaminated"
max_seq_length = 1536

[wandb]
project = "DEMO"
name = "demo_with_small_model_1.5B"

[checkpoint]
interval = 1
