[model]
name = "Qwen/Qwen3-0.6B"

[data]
name = "open-r1/codeforces-cots"
split = "solutions_w_editorials_decontaminated"
num_samples = 2

[wandb]
project = "DEMO"
name = "demo_with_small_model"

[checkpoint]
interval = 1
